### ISSUE TITLE
Time out in Container of Trasnsform

### ISSUE THREAD

**Issue by marcokonsultex** [aborroy/alfresco-transform-service-3.0.0#1]
Hello.

I used yeoman's project, changed it to use Transform in Cluster and applied a .json file configuring the Transform Engine Libreoffice to transform excel files only with x size. I also use a proxy (according to acs-transnform-cluster documentation) to distribute between the 4 containers I configured.
Alfresco version 7.1.1 and Alfresco Transform version 3.0.0.

I have a test example of an Excel spreadsheet with 8 Mb and it sends it to one of the Transform containers, soon afterwards it generates a convert error, but the container that received the Transform activity still runs for around 4 minutes this Transform and then release.

Is there any way to release the execution of this file in the container?

Another point, I used a json configuring the execution of Transform performing an override using this example:
{
  "transformers": [
    {
      "transformerName": "libreoffice",
      "supportedSourceAndTargetList": [
        {"sourceMediaType": "application/vnd.ms-excel", "maxSourceSizeBytes": 50, "targetMediaType": "text/html" },
        {"sourceMediaType": "application/vnd.ms-excel", "targetMediaType": "application/vnd.oasis.opendocument.spreadsheet" },
        {"sourceMediaType": "application/vnd.ms-excel", "targetMediaType": "application/vnd.oasis.opendocument.spreadsheet-template" },
        {"sourceMediaType": "application/vnd.ms-excel", "targetMediaType": "text/tab-separated-values" },
        {"sourceMediaType": "application/vnd.ms-excel", "priority": 45, "targetMediaType": "application/vnd.ms-excel" },
        {"sourceMediaType": "application/vnd.ms-excel", "priority": 155, "targetMediaType": "application/pdf" }
      ]
    }
  ]
}
and even so, it forwards the file to execute the Trasnform.

My configuration of proxy to transform cluster:
worker_processes 1;
events { worker_connections 2048; }
http {
    client_max_body_size 50M;	
    proxy_read_timeout 10;
    upstream loadbalancer {
       server transform-core-aio-1:8090;
       server transform-core-aio-2:8090;
       server transform-core-aio-3:8090;
       server transform-core-aio-4:8090;
    }
    server {
        location / {
            proxy_pass http://loadbalancer;
        }
    }
}

and each configuration of container in docker-compose.yml:
transform-core-aio-1:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
        mem_limit: 5120m
        environment:
            TRANSFORM_CONFIG_FILE_PDFOVERRIDESUPPORTED: "/modify-supported.json"
            JAVA_OPTS: "
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                -Dserver.tomcat.threads.max=12
                -Dserver.tomcat.threads.min=4
                -Dlogging.level.org.alfresco.transform.router.TransformerDebug=DEBUG
            "
        volumes:
                - ./modify-supported.json:/modify-supported.json

My big challenge is:
I want to generate a short and quick timeout when executing an Excel Transform (small and/or large files) and that is released from the container.

Can someone please help with some information about this? And who can elucidate this challenge for me?

If you need more data, you can request it, please.

Thanks

Marco

**Comment by aborroy** [comment]
Default HTTP Request timeout for LibreOffice transformer is 120s:

https://github.com/Alfresco/alfresco-transform-core/blob/master/engines/libreoffice/src/main/resources/application-default.yaml#L8

If that limit is reached, Repository cancels the request but the Transform process is still working till the transformation is down.

There is no control in Transform side, so I guess you cannot cancel the process by any means.

**Comment by marcokonsultex** [comment]
Angel good morning.

We have a question regarding the timeout configured with LibreOffice.

Wouldn't these 1,200,000 be 20 minutes?

For 20 seconds wouldn't that be 1,200? How is this time setup?

Regards

**Comment by aborroy** [comment]
Yep, sorry, I've included a wrong calculation. You're right.

**Comment by marcokonsultex** [comment]
Thanks Angel.
